openthread/ot-nrf528xx

CMakeLists.txt, src/nrf52811/README.md, src/nrf52833/README.md, src/nrf52840/README.md
This PR makes binaries and libraries generated at specified directory in nrf cmake build. I think putting all the binaries and libraries in one directory would be better. 
[PR#6127](https://github.com/openthread/openthread/pull/6127) in openthread repo.
=> [build] use bin and lib as output directory

src/nrf52811/transport-config.h, src/nrf52833/transport-config.h, src/nrf52840/transport-config.h, src/src/transport/uart.c
* [nrf528xx] ensure HWFC is triggered when SW buffer is full
* [nrf528xx] use UARTE peripheral for TX path
This is a copy of [#6442 from OT](https://github.com/openthread/openthread/pull/6442)
=> [uart] ensure HWFC is triggered when SW buffer is full

src/src/transport/uart.c
This PR is a proposition of a problem reported in https://github.com/openthread/openthread/issues/6623. Current CLI  implementation (UART variant) uses `otPlatUartFlush()` for corner case and crashes when it is not implemented. While it would be better to handle asynchronous transmissions in CLI I think that there is no strong reason to not implement this function.
Fixes https://github.com/openthread/openthread/issues/6623
=> [uart] implement otPlatUartFlush()

src/src/radio.c
Use new `otPlatRadioEnableCsl` with `aShortAddr` being passed.
Depends on:
=> [low-power] adapt to changes in EnableCsl API

src/src/radio.c
This commit splits OPENTHREAD_CONFIG_MLE_LINK_METRICS_ENABLE macro into
two subsequent ones:
- OPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE
- OPENTHREAD_CONFIG_MLE_LINK_METRICS_INITIATOR_ENABLE
Signed-off-by: canisLupus1313 <85344032+canisLupus1313@users.noreply.github.com>
=> [link-metrics] split OPENTHREAD_CONFIG_MLE_LINK_METRICS_ENABLE macro

src/src/radio.c
This commit updates `radio.c` to remove uses of OT core internal
macros (e.g. `VerifyOrExit`) and replaces then with the platform
util definitions (e.g. `otEXPECT`).
----
I think the inclusion of `common/code_utils.hpp` and use of the private/internal
OT macros in radio platform code was added in https://github.com/openthread/openthread/pull/5961.
=> [radio] remove use of OT core internal definitions/headers

.gitignore
This commit adds the `openthread/.gitignore` in this repository to ignore any intermediate
files generated by this project or openthread.
Also ignores `*.hex` and `*.zip` files which are usually nRF528XX firmwares.
=> [git] add .gitignore file

third_party/NordicSemiconductor/drivers/radio/nrf_802154_config.h, third_party/NordicSemiconductor/drivers/radio/rsch/raal/nrf_raal_config.h
ot-nrf528xx uses the compile option
`-DNRF_802154_PROJECT_CONFIG=\"platform-config.h\"` to specify the
Nordic library configuration file. Some build systems do not support this
usage.
This commit includes the default user implemented configuration header
file to avoid specifying the configuration file.
=> [config] include the default user configuration header

src/nrf52811/nrf52811.cmake, src/nrf52833/nrf52833.cmake, src/nrf52840/nrf52840.cmake
Sample usage:
```
./script/build nrf52840 UART_trans  -DOT_UART_BAUDRATE=460800
```
=> [uart] add a cmake cache entry for specifying Baud rate

src/src/radio.c
For a CSL retransmission, avoid to inject the CSL IE since it would break the frame encryption.
=> [csl] avoid overwritting IEs for retransmissions

src/src/transport/usb-cdc-uart.c
Address issue #178:
OpenThread CLI output may be lost in USB CDC mode because
otPlatUartFlush is not implemented
Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>
=> [usb] implement `otPlatUartFlush` for USB

src/src/transport/spi-slave.c
Issue #7224 was reported that aTransactionLength parameter of SPI
otPlatSpiSlaveTransactionCompleteCallback callback is used incorrectly
by passing only received buffer size instead of real transaction
length.
The driver does not provide functionality to get this value, however in
this case providing maximum of the received and transmitted lengths
should do the trick.
Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>
Fixes https://github.com/openthread/openthread/issues/7224
=> [spi] fix issue with SPI transaction being too short

src/nrf52833/README.md, src/nrf52840/README.md
Added note to samples that nRF5 SDK is in maintenance only,
and new projects should use nRF Connect SDK.
Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>
=> [docs] add mention of nRF Connect SDK

src/src/transport/usb-cdc-uart.c
This commit adds triggering events on usbd while waiting for end of
cdc uart transmission. aLso ensures that tx buffers aren't modified when
transmission is ongoing.
addresses #237
=> [usb] add usbd event processing trigger when flush function is called

README.md
Replace link to openthread-users Google Group with link to GitHub OpenThread Discussions and clarify issue reporting links.
=> Update links to support in README

src/CMakeLists.txt, src/src/crypto.c, src/src/platform-nrf5.h, src/src/system.c, third_party/NordicSemiconductor/CMakeLists.txt
The radio driver calls the `nrf_802154_tx_started` after the `SFD` is
sent. The radio driver must complete the encryption of the first byte
of the payload before it is sent in the function `nrf_802154_tx_started`.
The chip nrf52811 is using the software AES ECB encryption, the
encryption speed is slow. Sometimes, it causes the first received payload
byte is not encrypted.
This PR uses the ECB hardware to implement the crypto platform API
to improve the encryption speed.
=> [crypto] add crypto platform API

src/src/platform-nrf5.h, third_party/NordicSemiconductor/nrfx/hal/nrf_ecb.c
After #369 introduced the usage of the ECB peripheral, `AesEcb::Encrypt`
would assert under heavy traffic situation in FTD mode due to the
counter reaching 0 value in `nrf_ecb_crypt`.
Reproduction has a 100% rate when using `tcp benchmark` command when
the device is configured as TCP listener.
This commit disables interrupts while ECB encryption is taking place.
It also removes duplicated declaration of `nrf5CryptoInit`.
=> [crypto] fix ECB module assertion under heavy traffic

src/src/alarm.c
This commit prioritizes usec timer over msec. Doing so improves CSL by helping scheduling timeslots on IEEE 802.15.4 with lower miss rate.
Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>
=> [alarm] prioritize usec timer over msec

src/src/diag.c
This change aligns returned error codes with new description from https://github.com/openthread/openthread/pull/8538
=> [diag] gpio diag commands error alignment

src/src/radio.c
This commit implements the new OT radio platform API which updates the MAC Frame Counter value only if the new given value is larger than the current value.
----
This is related to https://github.com/openthread/openthread/pull/8607 (should be merged after this PR).
=> [radio] add `otPlatRadioSetMacFrameCounterIfLarger()`

src/src/transport/uart.c
Align implementation of `otPlatUartSend` in uart.c to be similar with usb-cdc-uart.c
=> [uart] fix uart transport in cli

src/src/radio.c
The PR adds missing initialization of noise floor in link metrics
module. Without the PR, the link margin obtained in link metrics
enhanced-ack probing is incorrect.
On simulation platform, the initialization is done:
https://github.com/openthread/openthread/blob/main/examples/platforms/simulation/radio.c#L503
=> [link-metrics] add missing initialization of noisefloor for link metrics

script/build
This disables test builds when building samples.
=> [cmake] set `BUILD_TESTING` to `OFF`

third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c
The flag `psdu_being_received` is set to True when the radio driver receives the FC field of the data frame, and the flag will be cleared after the ACK is sent out in PHYEND handler if the ACK is required. Sometimes, the ACK is failed to be sent out, which causes the flag to be set to True forever. Then the radio driver can't send out any frames.
The sdk-nrfxlib (https://github.com/nrfconnect/sdk-nrfxlib/blob/main/nrf_802154/driver/src/nrf_802154_trx.c#L2492) clears the flag `psdu_being_received` in the CRCOK handler rather than PHYEND handler. This commit clears the flag `psdu_being_received` in CRCOK handler to avoid the `psdu_being_received` being permanently set to True.
Issue link: https://nrfsupport.atlassian.net/browse/NRF11-73
=> [nrf528xx] clear psdu_being_received in CRCOK handler

src/src/radio.c
The function to query the csl uncertainty has an incorrect name in the nrf code `otPlatRadioGetCslClockUncertainty` as opposed to `otPlatRadioGetCslUncertainty`. See https://github.com/openthread/openthread/blob/main/include/openthread/platform/radio.h#L1212 .
Since openthread has a default weak implementation of the function this doesn't cause any linker errors but instead silently uses 255 which effectively increases the CSL window by a constant 10ms.
=> [radio] fix csl uncertainty reporting max value

src/src/radio.c, third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_csma_ca.c, third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_csma_ca.h, third_party/NordicSemiconductor/drivers/radio/nrf_802154.c, third_party/NordicSemiconductor/drivers/radio/nrf_802154.h
The current radio driver doesn't handle the `mInfo.mTxInfo.mMaxCsmaBackoffs` field of the tx frame. The maximum number of CSMA-CA backoffs is set to the fixed value `4`.
This commit sets the maximum number of CSMA-CA backoffs to `mInfo.mTxInfo.mMaxCsmaBackoffs`.
=> [radio] add `mInfo.mTxInfo.mMaxCsmaBackoffs` support

src/src/radio.c, third_party/NordicSemiconductor/drivers/radio/nrf_802154.c, third_party/NordicSemiconductor/drivers/radio/nrf_802154.h
The `mInfo.mRxInfo.mTimestamp` represents the end time of the SFD of the received frame. But the radio driver sets the `mInfo.mRxInfo.mTimestamp` value to the first symbol time of the received frame.
This commit adds a method `nrf_802154_timestamp_end_to_phr_convert()` to calculate the end time of the SFD of the received frame. The method comes from the `sdk-nrfxlib`.
=> [radio] correct the `mInfo.mRxInfo.mTimestamp` value of recevied frames

src/src/radio.c
The CSL transmitter is using the OT defined default CSL accuracy and uncertainty values. 
This commit enables `otPlatRadioGetCslAccuracy()` and `otPlatRadioGetCslUncertainty()`  when the CSL transmitter is enabled to make the CSL transmitter to use correct CSL accuracy and uncertainty values.
=> [radio] use correct csl accuracy and uncertainty values when the CSL transmitter is enabled

src/src/radio.c
This commit removes otPlatDiagRadioTransmitDone() and otPlatDiagRadioReceiveDone() API.
Depends-On: https://github.com/openthread/openthread/pull/11615
=> [diag] align with OT radio platform API changes
